### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by best-lucky1030** [qhanw/qhanw#1]
@qhanw 
Do you have English version of this readme?
If you make that for me, will appreciate to you. 🙇‍♂️

**Comment by qhanw** [comment]
My English is not very good. I hope you can understand it.

**Comment by qhanw** [comment]
> @qhanw Do you have English version of this readme? If you make that for me, will appreciate to you. 🙇‍♂️

I haven't dealt with it for so long because my English is not very good. I hope you can understand it.
